# Generated by Django 4.2.7 on 2023-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('categorydetails', models.CharField(max_length=1000)),
                ('categoryimage', models.ImageField(default='cat_def.jpg', upload_to='catimg')),
            ],
            options={
                'verbose_name': 'Food Category',
            },
        ),
    ]
